name: Snapshot (amd64)

on:
  workflow_dispatch:
    inputs:

jobs:
  snapshot-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      registry:
        image: registry:3
        ports:
          - 5000:5000
    steps:
      - name: Get BUILDINFO epoch
        env:
          URL: https://cdn.openbsd.org/pub/OpenBSD/snapshots/amd64/BUILDINFO
        run: |
            curl $URL | sed -e \
                's/Build date: \([0-9]*\) .*/BUILD_DATE=\1/' >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v5

      - name: Local file edits for Docker compatibility
        run: |
            sed -i -e '/RUN sh -c/s/RUN/RUN --security=insecure/' \
                $GITHUB_WORKSPACE/oci/cloud-init-amd64/Containerfile
            sed -i -e '/RUN sh -c/s/RUN/RUN --security=insecure/' \
                $GITHUB_WORKSPACE/oci/openbsd-amd64/Containerfile

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--allow-insecure-entitlement security.insecure"
          driver-opts: network=host

      - name: Build cloud-init
        uses: docker/build-push-action@v6
        with:
          allow: security.insecure
          build-args: |
              VERSION=snapshots
              CPU=4
              MEM=16G
              KVM=-enable-kvm
          context: "./oci/cloud-init-amd64"
          file: "./oci/cloud-init-amd64/Containerfile"
          build-contexts: |
              port=.
          tags: localhost:5000/site-cloud-init:latest
          push: true

      - name: Build
        uses: docker/build-push-action@v6
        with:
          allow: security.insecure
          build-args: |
              VERSION=snapshots
              SITE=localhost:5000/site-cloud-init:latest
              CPU=4
              MEM=16G
              KVM=-enable-kvm
          context: "./oci/openbsd-amd64"
          file: "./oci/openbsd-amd64/Containerfile"
          build-contexts: |
              port=.
          tags: |
              ghcr.io/3405691582/openbsd-amd64:${{ env.BUILD_DATE }}
              ghcr.io/3405691582/openbsd-amd64:latest
          provenance: false
          push: true
